import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>IP Address Tracker</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../images/favicon-32x32.png" />
      </Head>

      <main className={styles.main}>
        <div className="form_container"> 
          <h1>IP Address Tracker</h1>
          <div>
            {/* <label for="price" class="block text-sm font-medium text-gray-700">Price</label> */}
            <div class="mt-1 relative rounded-md shadow-sm">
              <input type="text" name="price" id="price" class="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-7 pr-12 sm:text-sm border-gray-300 rounded-md" placeholder="Search for any IP address or domain" />
              <div class="absolute inset-y-0 right-0 flex items-center bg-black text-white">
                <button>></button>
              </div>
            </div>
          </div>
        </div>
        <div className="ip_data_container">
          <div>IP Address</div>
          <div>Location</div>
          <div>Timezone</div>
          <div>UTC () add offset value dynamically using the API )</div>  
          <div>ISP</div>

        </div>
        <div className="map_container"></div>

      </main>

      <footer className={styles.footer}>
        <div class="attribution">
          Challenge by <a href="https://www.frontendmentor.io?ref=challenge" target="_blank">Frontend Mentor</a>. 
          Coded by <a href="#">Your Name Here</a>.
        </div>
        <div>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </div>
      </footer>
    </div>
  )
}
